### ISSUE TITLE
Uppercase-Tags ignored during rendering

### ISSUE THREAD

**Issue by FLE92** [smmoosavi/jsx-xml#3]
Hello everyone,

i am new on GitHub an not sure if this is the right place to submit such an issue like mine. I am trying to use uppercase tags, but they are ignored during rendering. Have you any idea what could be the reason for that?  Here is my code:
```
  const Test = ()=>{}
  const xml = render(<div><Test>Star</Test>Click</div>) // jsx input
  console.log(xml)
```
During rendering the Test-tag is ignored. I get only the folwing output:
``` <?xml version="1.0"?><div>Click</div> ```

Thanks for help!

**Comment by smmoosavi** [comment]
Hello,

check this:
```js
  const Test = 'Test'
```

**Comment by FLE92** [comment]
Hello, many thanks for your quick response! Now it works and does a good job! :-) Greetings from Bavaria
