### ISSUE TITLE
Is there a possibility to insert colons in attribute names?

### ISSUE THREAD

**Issue by FLE92** [smmoosavi/jsx-xml#4]
Hello again, is there any possibility to add attributes with colons like:
``` <Test abc:def="teststring"/> ```
Thanks for help!

**Comment by FLE92** [comment]
(Of course it works with lodash, but that's not an ideal solution...)

**Comment by smmoosavi** [comment]
In JSX syntaxy you can't add colons. but you can pass an object
```jsx
const Test = 'Test'
const props = { 'abc:def': "teststring" }

const xml = <Test {...props} />
```

or create object inline

```jsx
const xml = <Test {...{ 'abc:def': "teststring" }} />
```

**Comment by smmoosavi** [comment]
update: typescript v5.1 will support ["Namespaced JSX Attributes"][ts]. I'm not tested that yet.

[ts]: https://devblogs.microsoft.com/typescript/announcing-typescript-5-1-beta/#namespaced-jsx-attributes
