### ISSUE TITLE
JSX Sytax Breaking custom namespace element

### ISSUE THREAD

**Issue by sacredgaming** [smmoosavi/jsx-xml#8]
I understand we can spread objects to declare namespaces, but I can't seem to figure out how we can then use those namespaces to build an rss feed. 

Example here

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <item>
       <content:encoded>
       </content:encoded>
   </item>
  </channel>
```

I've seen ways using React.createElement to solve this but that throws a validation error for me, at least in our environment. I assume this is because xml builder is expecting a string not a symbol and jsx-xml does render it the same way React does. Either way I am still digging but if anyone has a solution, I would appreciate it. 

Update: It appears as though I can just return it as a string and use the Raw component to wrap it.

**Comment by smmoosavi** [comment]
## Problem
namespace is not part of jsx syntax and you will get compilte time error if you use namespace syntax

```
SyntaxError: src/index.js: Namespace tags are not supported. ReactJSX is not XML.
  26 | console.log(render(
  27 |   <test>
> 28 |     <test:foo/>
     |      ^
  29 |   </test>,
  30 |   options))
  31 | 

```
## Solution
You can define a string variable:

example:

```jsx
const TestFoo = 'test:foo'; // capital T is important
const xml = render(
  <test>
      <TestFoo/>
  </test>,
  options)
```
output:
```
<test>
  <test:foo/>
</test>
```
